"""empty message

Revision ID: d92984ec62bd
Revises: d92d981ffcf0
Create Date: 2016-08-16 22:36:19.620941

"""

# revision identifiers, used by Alembic.
revision = 'd92984ec62bd'
down_revision = 'd92d981ffcf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('city', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'city')
    ### end Alembic commands ###
