"""empty message

Revision ID: d92d981ffcf0
Revises: None
Create Date: 2016-08-10 21:26:40.147923

"""

# revision identifiers, used by Alembic.
revision = 'd92d981ffcf0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('shop',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zip', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('transaction',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('creditor_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('attachment', sa.LargeBinary(), nullable=True),
    sa.Column('comment', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['creditor_id'], ['person.pid'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.sid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('asset',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('trans_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('debitor_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=150), nullable=True),
    sa.Column('tag', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['debitor_id'], ['person.pid'], ),
    sa.ForeignKeyConstraint(['trans_id'], ['transaction.tid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    op.drop_table('transaction')
    op.drop_table('shop')
    op.drop_table('person')
    ### end Alembic commands ###
