"""empty message

Revision ID: e705133fe4c4
Revises: d92984ec62bd
Create Date: 2016-08-16 23:28:03.916598

"""

# revision identifiers, used by Alembic.
revision = 'e705133fe4c4'
down_revision = 'd92984ec62bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'quantity')
    ### end Alembic commands ###
